name: 翻訳フィードバック / Translation Feedback
description: 日本語訳の誤りや改善提案を報告する
labels: ["translation"]
body:
  - type: markdown
    attributes:
      value: |
        > **注意 / Notice**
        > このエクステンションは非公式のコミュニティプロジェクトです。Framerが公式に製品の動作を完全に保証するものではありません。
        > This extension is an unofficial community project, unaffiliated with Framer. It does not guarantee complete accuracy of product behavior.

        翻訳の誤りや改善提案のみを対象としています。製品のバグや機能リクエストはこちらでは受け付けていません。
        This template is for translation issues and suggestions only. Product bugs or feature requests are out of scope.

  - type: input
    id: original
    attributes:
      label: 元の英語テキスト / Original English text
      placeholder: 例) Line Height
    validations:
      required: true

  - type: input
    id: current
    attributes:
      label: 現在の日本語訳 / Current Japanese translation
      placeholder: 例) 線の高さ
    validations:
      required: true

  - type: input
    id: suggested
    attributes:
      label: 提案する日本語訳 / Suggested Japanese translation
      placeholder: 例) 行の高さ
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由・補足 / Reason or context
      placeholder: なぜこの訳が適切か、参考資料があれば記載してください。
    validations:
      required: false
