// src/content/index.ts

console.log("🚀 Framer Japanese Booster: 起動");

/**
 * 1. 翻訳辞書 (提供いただいた全リストを保持)
 */
const translations: Record<string, string> = {
  // メインナビゲーション
  "Pages": "ページ",
  "Layers": "レイヤー",
  "Assets": "アセット",
  "Components": "コンポーネント",
  "Insert": "挿入",
  "Layout": "レイアウト",
  
  // プロパティパネル - サイズ・位置
  "Width": "幅",
  "Height": "高さ",
  "Position": "位置",
  "Size": "サイズ",
  "X": "X",
  "Y": "Y",
  "Left": "左",
  "Right": "右",
  "Top": "上",
  "Bottom": "下",
  "Center": "中央",
  "Constraints": "制約",
  
  // プロパティパネル - スタイル
  "Fill": "塗り",
  "Stroke": "線",
  "Background": "背景",
  "Border": "境界線",
  "Radius": "角丸",
  "Corner Radius": "角丸",
  "Border Radius": "角丸",
  "Opacity": "不透明度",
  "Blend Mode": "合成モード",
  "Effects": "エフェクト",
  "Shadow": "影",
  "Blur": "ぼかし",
  "Gradient": "グラデーション",
  
  // プロパティパネル - レイアウト
  "Padding": "余白",
  "Margin": "マージン",
  "Gap": "間隔",
  "Spacing": "間隔",
  "Align": "整列",
  "Alignment": "整列",
  "Align Items": "アイテム整列",
  "Align Content": "コンテンツ整列",
  "Justify": "配置",
  "Justify Content": "コンテンツ配置",
  "Distribute": "配置",
  "Flex": "フレックス",
  "Flex Direction": "フレックス方向",
  "Flex Wrap": "フレックス折り返し",
  "Grid": "グリッド",
  "Grid Template": "グリッドテンプレート",
  "Grid Gap": "グリッド間隔",
  
  // プロパティパネル - タイポグラフィ
  "Font": "フォント",
  "Font Size": "フォントサイズ",
  "Font Weight": "フォント太さ",
  "Line Height": "行の高さ",
  "Letter Spacing": "文字間隔",
  "Text Align": "テキスト整列",
  "Text Transform": "テキスト変換",
  "Text Decoration": "テキスト装飾",
  
  // プロパティパネル - その他
  "Transform": "変形",
  "Rotation": "回転",
  "Scale": "拡大縮小",
  "Skew": "傾斜",
  "Overflow": "はみ出し",
  "Z Index": "Z順序",
  "Pointer Events": "ポインターイベント",
  "Cursor": "カーソル",
  "Display": "表示",
  "Visibility": "表示状態",
  "Clip": "クリップ",
  "Mask": "マスク",
  
  // アクション・操作
  "Edit": "編集",
  "Delete": "削除",
  "Duplicate": "複製",
  "Copy": "コピー",
  "Paste": "貼り付け",
  "Undo": "元に戻す",
  "Redo": "やり直し",
  "Group": "グループ化",
  "Ungroup": "グループ解除",
  "Lock": "ロック",
  "Unlock": "ロック解除",
  "Hide": "非表示",
  "Show": "表示",
  
  // その他のUI要素
  "Settings": "設定",
  "Preferences": "環境設定",
  "Export": "エクスポート",
  "Import": "インポート",
  "Save": "保存",
  "Open": "開く",
  "New": "新規",
  "Close": "閉じる",
  "Cancel": "キャンセル",
  "Apply": "適用",
  "OK": "OK",
  "Reset": "リセット",
  "Default": "デフォルト",
  "Custom": "カスタム",
  "None": "なし",
  "Auto": "自動",
  "Fixed": "固定",
  "Relative": "相対",
  "Absolute": "絶対",
  "Sticky": "スティッキー",
  "Static": "静的",
  
  // 状態・モード
  "Preview": "プレビュー",
  "Design": "デザイン",
  "Code": "コード",
  "Prototype": "プロトタイプ",
  "Responsive": "レスポンシブ",
  "Breakpoint": "ブレークポイント",
  
  // アニメーション
  "Animation": "アニメーション",
  "Transition": "トランジション",
  "Duration": "継続時間",
  "Delay": "遅延",
  "Easing": "イージング",
  "Timing": "タイミング",
  
  // インタラクション
  "Interaction": "インタラクション",
  "Trigger": "トリガー",
  "Action": "アクション",
  "On Click": "クリック時",
  "On Hover": "ホバー時",
  "On Load": "読み込み時",
  "Navigate": "ナビゲート",
  "Scroll": "スクロール",
  "Open Overlay": "オーバーレイを開く",
  "Close Overlay": "オーバーレイを閉じる",
  
  // データ・変数
  "Variables": "変数",
  "Data": "データ",
  "Binding": "バインディング",
  "Expression": "式",
  
  // カラー
  "Color": "色",
  "Hue": "色相",
  "Saturation": "彩度",
  "Brightness": "明度",
  "Alpha": "アルファ",
  "Hex": "16進数",
  "RGB": "RGB",
  "HSL": "HSL",
  
  // 画像・メディア
  "Image": "画像",
  "Video": "動画",
  "Audio": "音声",
  "Fit": "フィット",
  "Cover": "カバー",
  "Contain": "含む",
  "Fill Image": "塗りつぶし",
  
  // コンポーネント関連
  "Instance": "インスタンス",
  "Override": "オーバーライド",
  "Variant": "バリアント",
  "State": "状態",
  "Property": "プロパティ",
  "Slot": "スロット",
  
  // レスポンシブ・ブレークポイント
  "Mobile": "モバイル",
  "Phone": "モバイル",
  "Tablet": "タブレット",
  "Desktop": "デスクトップ",
  "Viewport": "ビューポート",
  "Device": "デバイス",
  
  // その他
  "Search": "検索",
  "Filter": "フィルター",
  "Sort": "並び替え",
  "Select": "選択",
  "All": "すべて",
  "Selected": "選択中",
  "Name": "名前",
  "Type": "タイプ",
  "Value": "値",
  "Unit": "単位",
  "px": "px",
  "%": "%",
  "em": "em",
  "rem": "rem",
  "vh": "vh",
  "vw": "vw",
  "Archive": "アーカイブ",

  // コメント・コラボレーション
  "Comment": "コメント",
  "Comments": "コメント",
  "Resolve": "解決",
  "Unresolve": "未解決に戻す",
  "Reply": "返信",
  "Mention": "メンション",

  // チーム・ワークスペース
  "Team": "チーム",
  "Workspace": "ワークスペース",
  "Invite Member": "メンバーを招待",
  "Members": "メンバー",
  "Guest": "ゲスト",
  "Editor": "エディター",
  "Admin": "管理者",

  // バージョン履歴
  "Version History": "バージョン履歴",
  "Restore Version": "バージョンを復元",
  "Auto-saved": "自動保存済み",

  // スナップ
  "Snap": "スナップ",
  "Snap to Grid": "グリッドにスナップ",
  "Snap to Objects": "オブジェクトにスナップ",
  "Snap to Pixel": "ピクセルにスナップ",

  // デザイントークン
  "Design Token": "デザイントークン",
  "Token": "トークン",
  "Tokens": "トークン",

  // コードコンポーネント
  "Code Component": "コードコンポーネント",
  "Smart Component": "スマートコンポーネント",

  // エラー・ステータス
  "Error": "エラー",
  "Warning": "警告",
  "Loading": "読み込み中",
  "Saving": "保存中",
  "Connecting": "接続中",
  "Disconnected": "切断",
  "Offline": "オフライン",
  "Online": "オンライン",
  
  // UI要素・アクション
  "Add": "追加",
  "Add Collection": "コレクションを追加",
  "Add Locale": "ロケールを追加",
  "Add Script": "スクリプトを追加",
  "Add Step": "ステップを追加",
  "Add a tracking ID": "トラッキングIDを追加",
  "Add…": "追加…",
  "Back": "戻る",
  "Change": "変更",
  "Changes": "変更",
  "Choose Image…": "画像を選択…",
  "Clear": "クリア",
  "Clear All": "すべてクリア",
  "Click": "クリック",
  "Confirm": "確認",
  "Connect": "接続",
  "Connect Domain": "ドメインを接続",
  "Connect an existing domain": "既存のドメインを接続",
  "Connect your own domain": "独自のドメインを接続",
  "Continue Editing": "編集を続ける",
  "Copy Clipboard": "クリップボードにコピー",
  "Copy Import": "インポートをコピー",
  "Copy URL": "URLをコピー",
  "Create Redirect": "リダイレクトを作成",
  "Create a redirect to maintain": "維持するためのリダイレクトを作成",
  "Crop": "トリミング",
  "Crop Image": "画像をトリミング",
  "Discard Item": "アイテムを破棄",
  "Dismiss popup": "ポップアップを閉じる",
  "Done": "完了",
  "Download": "ダウンロード",
  "Drag": "ドラッグ",
  "Drop image": "画像をドロップ",
  "Edit Code": "コードを編集",
  "Edit Component": "コンポーネントを編集",
  "Edit Fields": "フィールドを編集",
  "Edit Step": "ステップを編集",
  "Find": "検索",
  "Ignore All": "すべて無視",
  "Invite": "招待",
  "New A/B Test": "A/Bテストを新規作成",
  "New Code File": "コードファイルを新規作成",
  "New Component": "コンポーネントを新規作成",
  "New File": "ファイルを新規作成",
  "New File…": "ファイルを新規作成…",
  "New Folder": "フォルダを新規作成",
  "New Issue": "課題を新規作成",
  "New Item": "アイテムを新規作成",
  "New Locale": "ロケールを新規作成",
  "New Set": "セットを新規作成",
  "New Style": "スタイルを新規作成",
  "New Tab": "タブを新規作成",
  "New Template": "テンプレートを新規作成",
  "New URL": "URLを新規作成",
  "Next Link": "次のリンク",
  "Next page": "次のページ",
  "No": "いいえ",
  "Open in Overlay": "オーバーレイで開く",
  "Publish": "公開",
  "Refresh": "更新",
  "Rename": "名前を変更",
  "Replace": "置換",
  "Request Trial": "トライアルをリクエスト",
  "Resume": "再開",
  "Rotate": "回転",
  "Save Draft": "下書きを保存",
  "Saved": "保存済み",
  "Select…": "選択…",
  "Send": "送信",
  "Send AI Message": "AIメッセージを送信",
  "Unlink": "リンクを解除",
  "Unpublish": "公開を取り消し",
  "Upgrade": "アップグレード",
  "Upgrade Now": "今すぐアップグレード",
  "Upload": "アップロード",
  "View": "表示",
  "View Only": "閲覧のみ",
  "View on Canvas": "キャンバスで表示",
  "Yes": "はい",
  "Zoom to 100%": "100%にズーム",
  "Zoom to Fit": "フィットにズーム",
  
  // 機能・機能名
  "A/B Tests": "A/Bテスト",
  "A/B testing": "A/Bテスト",
  "AI Style": "AIスタイル",
  "AI Translate": "AI翻訳",
  "AI-powered design tools": "AI搭載デザインツール",
  "About": "について",
  "Accessibility": "アクセシビリティ",
  "All members can access": "すべてのメンバーがアクセス可能",
  "Alt": "代替テキスト",
  "Analytics": "アナリティクス",
  "Annual": "年間",
  "Annual Only": "年間のみ",
  "Any": "任意",
  "Anyone with link can view": "リンクを持つ人は誰でも閲覧可能",
  "Appear": "表示",
  "Apple Music": "Apple Music",
  "Apple Podcasts": "Apple Podcasts",
  "Apple Touch Icon": "Apple Touchアイコン",
  "Apply to All H2s": "すべてのH2に適用",
  "Approve": "承認",
  "Auto (Lossless)": "自動（ロスレス）",
  "Automatic Locale": "自動ロケール",
  "Average Session": "平均セッション",
  "Base": "ベース",
  "Based On": "基準",
  "Basic": "基本",
  "Basics": "基本",
  "Blog": "ブログ",
  "Blog Posts": "ブログ投稿",
  "Body": "本文",
  "Body small": "本文（小）",
  "Bounce Rate": "バウンス率",
  "Browse Plugins": "プラグインを閲覧",
  "Built-in SEO": "組み込みSEO",
  "CMS": "CMS",
  "CMS Collections": "CMSコレクション",
  "CMS Export": "CMSエクスポート",
  "CMS Fields": "CMSフィールド",
  "CSV Import": "CSVインポート",
  "Campaign Tracking": "キャンペーントラッキング",
  "Canonical URL": "正規URL",
  "Carousel": "カルーセル",
  "Changelog Page": "変更履歴ページ",
  "Chrome Extension": "Chrome拡張機能",
  "Client": "クライアント",
  "Code Block": "コードブロック",
  "Code Overrides": "コードオーバーライド",
  "Collection": "コレクション",
  "Collections": "コレクション",
  "Colors": "色",
  "Columns": "列",
  "Common Regions": "共通リージョン",
  "Community": "コミュニティ",
  "Compare all plans and features": "すべてのプランと機能を比較",
  "Component": "コンポーネント",
  "Content": "コンテンツ",
  "Context Menu": "コンテキストメニュー",
  "Cookie Banner": "クッキーバナー",
  "Countdown": "カウントダウン",
  "Countries": "国",
  "Created": "作成日",
  "Creative": "クリエイティブ",
  "Creative Direction": "クリエイティブディレクション",
  "Cursor Chat": "カーソルチャット",
  "Custom Code": "カスタムコード",
  "Custom locale regions": "カスタムロケールリージョン",
  "Damping": "減衰",
  "Danger Zone": "危険ゾーン",
  "Dark": "ダーク",
  "Dark Theme": "ダークテーマ",
  "Date": "日付",
  "Deliverables": "成果物",
  "Description": "説明",
  "Devices": "デバイス",
  "Direction": "方向",
  "Docs": "ドキュメント",
  "Domains": "ドメイン",
  "Dot Lottie": "Dot Lottie",
  "Draft": "下書き",
  "Ease": "イージング",
  "Ease In": "イーズイン",
  "Ease In Out": "イーズインアウト",
  "Ease Out": "イーズアウト",
  "Editing Item": "編集中のアイテム",
  "Elements": "要素",
  "Em": "Em",
  "Email Signups": "メール登録",
  "Embed": "埋め込み",
  "Embeds": "埋め込み",
  "Empty Alt Text": "空の代替テキスト",
  "End": "終了",
  "Enterprise": "エンタープライズ",
  "Events and funnels": "イベントとファネル",
  "Everything from": "すべてから",
  "Examples": "例",
  "Explore": "探索",
  "Facebook": "Facebook",
  "Fallback": "フォールバック",
  "Fast and secure hosting": "高速で安全なホスティング",
  "Favicon": "ファビコン",
  "Featured": "おすすめ",
  "Fields": "フィールド",
  "File": "ファイル",
  "Filters": "フィルター",
  "Fit Content": "コンテンツにフィット",
  "Fit Text": "テキストにフィット",
  "Flexible limits": "柔軟な制限",
  "Focal Point": "焦点",
  "Form Builder": "フォームビルダー",
  "Form Settings": "フォーム設定",
  "Form Submit": "フォーム送信",
  "Forms": "フォーム",
  "Frame": "フレーム",
  "Framer": "Framer",
  "Framer Blog": "Framerブログ",
  "Framer Commerce": "Framer Commerce",
  "Framer Tips for Beginners": "初心者向けFramerのヒント",
  "Framer University": "Framer University",
  "Free": "無料",
  "Full": "フル",
  "Full Access": "フルアクセス",
  "Funnel": "ファネル",
  "Funnels": "ファネル",
  "GIF": "GIF",
  "General": "一般",
  "Get a free Framer subdomain": "無料のFramerサブドメインを取得",
  "Get template": "テンプレートを取得",
  "Glossary": "用語集",
  "Go to Dashboard": "ダッシュボードに移動",
  "Google Account": "Googleアカウント",
  "Google Analytics": "Googleアナリティクス",
  "Google Maps": "Googleマップ",
  "Google Sheets": "Googleスプレッドシート",
  "Grid Pattern": "グリッドパターン",
  "Grow": "拡大",
  "Guides": "ガイド",
  "H1": "H1",
  "H2": "H2",
  "H3": "H3",
  "H4": "H4",
  "Header": "ヘッダー",
  "Heading 1": "見出し1",
  "Heading 2": "見出し2",
  "Heading 3": "見出し3",
  "Heading 4": "見出し4",
  "Heading 5": "見出し5",
  "Heading 6": "見出し6",
  "Hero": "ヒーロー",
  "Hidden": "非表示",
  "Home": "ホーム",
  "Home Page Settings": "ホームページ設定",
  "Hover": "ホバー",
  "Hover / Pressed": "ホバー/押下",
  "Id": "ID",
  "Image 1": "画像1",
  "Image 2": "画像2",
  "Image 3": "画像3",
  "Image 4": "画像4",
  "Import Collection": "コレクションをインポート",
  "Inherit": "継承",
  "Inline Code": "インラインコード",
  "Instagram": "Instagram",
  "Instant": "即座",
  "Interactions": "インタラクション",
  "Interactive": "インタラクティブ",
  "Language": "言語",
  "Language Name": "言語名",
  "Large": "大",
  "Last 30 days": "過去30日間",
  "Latest": "最新",
  "Layout Direction": "レイアウト方向",
  "Learn": "学習",
  "Learn More": "詳細を見る",
  "Learn more": "詳細を見る",
  "Letter": "文字",
  "Library": "ライブラリ",
  "Light": "ライト",
  "Light Theme": "ライトテーマ",
  "Lightbox": "ライトボックス",
  "Line": "線",
  "Linear": "リニア",
  "Link": "リンク",
  "Link To": "リンク先",
  "LinkedIn": "LinkedIn",
  "Live Visitors": "ライブ訪問者",
  "Locale Selector": "ロケールセレクター",
  "Locales": "ロケール",
  "Localization": "ローカライゼーション",
  "Logo": "ロゴ",
  "Loop": "ループ",
  "Loops": "ループ",
  "Lottie": "Lottie",
  "MP3": "MP3",
  "Marketplace": "マーケットプレイス",
  "Masonry": "メイソンリー",
  "Mass": "質量",
  "Max Length": "最大長",
  "Max Width": "最大幅",
  "Media": "メディア",
  "Medium": "中",
  "Menu Icons": "メニューアイコン",
  "Menu Mixed": "メニュー（混合）",
  "Menu Rows": "メニュー行",
  "Menu Simple": "メニュー（シンプル）",
  "Menu Split": "メニュー（分割）",
  "Menu Subline": "メニュー（サブライン）",
  "Menus": "メニュー",
  "Micro": "マイクロ",
  "Min Max": "最小最大",
  "Missing": "不足",
  "Mixed": "混合",
  "Multi-site proxy": "マルチサイトプロキシ",
  "Multiple locales": "複数ロケール",
  "Navigation": "ナビゲーション",
  "No Assets Found": "アセットが見つかりません",
  "No data available for the": "データが利用できません",
  "No data for the selected month": "選択した月のデータがありません",
  "Off": "オフ",
  "Old URL": "旧URL",
  "On": "オン",
  "Opt out of the HTML to Framer": "HTML to Framerから除外",
  "Other": "その他",
  "Over Limit": "制限超過",
  "Over limits": "制限超過",
  "Overlays": "オーバーレイ",
  "Overview": "概要",
  "Owner": "所有者",
  "Page": "ページ",
  "Page Description": "ページ説明",
  "Page Images": "ページ画像",
  "Page Settings": "ページ設定",
  "Pageview": "ページビュー",
  "Pageviews": "ページビュー",
  "Paragraph": "段落",
  "Password": "パスワード",
  "Password Protection": "パスワード保護",
  "Paste Collection": "コレクションを貼り付け",
  "Path": "パス",
  "Per month, billed yearly": "月額（年払い）",
  "Permissions": "権限",
  "Personal Page": "個人ページ",
  "Physics": "物理",
  "Pill": "ピル",
  "Placeholder": "プレースホルダー",
  "Plan Limit": "プラン制限",
  "Plans": "プラン",
  "Plugins": "プラグイン",
  "Popular": "人気",
  "Portfolio": "ポートフォリオ",
  "Position & Size": "位置とサイズ",
  "Premium CDN": "プレミアムCDN",
  "Preserve URL parameters (like": "URLパラメータを保持（例：",
  "Press": "押下",
  "Primary": "プライマリ",
  "Priority support": "優先サポート",
  "Pro": "Pro",
  "Project": "プロジェクト",
  "Project Link": "プロジェクトリンク",
  "Projects": "プロジェクト",
  "Published at": "公開日時",
  "Published by": "公開者",
  "Px": "Px",
  "Quick Actions…": "クイックアクション…",
  "Ready": "準備完了",
  "Recents": "最近",
  "Redirects": "リダイレクト",
  "Referrer": "参照元",
  "Region": "リージョン",
  "Rel": "Rel",
  "Relational CMS": "リレーショナルCMS",
  "Rem": "Rem",
  "Required": "必須",
  "Resolution": "解像度",
  "Role": "役割",
  "Roles and permissions": "役割と権限",
  "Rows": "行",
  "Scroll Animation": "スクロールアニメーション",
  "Scroll Section": "スクロールセクション",
  "Scroll Speed": "スクロール速度",
  "Scroll Transform": "スクロール変形",
  "Scroll Variant": "スクロールバリアント",
  "Sections": "セクション",
  "Selection": "選択",
  "Shadows": "影",
  "Show Debug Bar": "デバッグバーを表示",
  "Show UI": "UIを表示",
  "Show page in Site Search": "サイト検索にページを表示",
  "Show page in search engines": "検索エンジンにページを表示",
  "Site Description": "サイト説明",
  "Site Images": "サイト画像",
  "Site Language": "サイト言語",
  "Site Title": "サイトタイトル",
  "Site redirects": "サイトリダイレクト",
  "Slideshow": "スライドショー",
  "Slug": "スラッグ",
  "Slug is required": "スラッグは必須です",
  "Small": "小",
  "Social": "ソーシャル",
  "Social Preview": "ソーシャルプレビュー",
  "Sort Alphabetically": "アルファベット順に並び替え",
  "Sort Layers Alphabetically": "レイヤーをアルファベット順に並び替え",
  "Sources": "ソース",
  "Space Around": "周囲にスペース",
  "Space Between": "間隔",
  "Space Evenly": "均等にスペース",
  "Spring": "スプリング",
  "Stack": "スタック",
  "Staging": "ステージング",
  "Staging & Versions": "ステージングとバージョン",
  "Staging and instant rollback": "ステージングと即座のロールバック",
  "Star": "スター",
  "Start": "開始",
  "Start with AI": "AIで開始",
  "Status": "ステータス",
  "Steps": "ステップ",
  "Stiffness": "剛性",
  "Styleguide": "スタイルガイド",
  "Styles": "スタイル",
  "Subscribe": "購読",
  "Tag": "タグ",
  "Teaser": "ティーザー",
  "Templates": "テンプレート",
  "Text": "テキスト",
  "Text Area": "テキストエリア",
  "Thumbnail": "サムネイル",
  "Ticker": "ティッカー",
  "Tile": "タイル",
  "Time": "時間",
  "Time & Date": "日時",
  "Title": "タイトル",
  "To Review": "レビュー待ち",
  "Total Bandwidth": "総帯域幅",
  "Total Pageviews": "総ページビュー",
  "Tracking": "トラッキング",
  "Transforms": "変形",
  "Translate": "翻訳",
  "Tutorials": "チュートリアル",
  "Twitter": "Twitter",
  "URL": "URL",
  "Unique Visitors": "ユニーク訪問者",
  "Uniques": "ユニーク",
  "Unsaved Changes": "未保存の変更",
  "Updated": "更新日",
  "Usage": "使用量",
  "Utility": "ユーティリティ",
  "Variant 1": "バリアント1",
  "Variant 2": "バリアント2",
  "Variant 3": "バリアント3",
  "Vector": "ベクター",
  "Vectors": "ベクター",
  "Version": "バージョン",
  "Versions": "バージョン",
  "Viewing now": "現在閲覧中",
  "Vimeo": "Vimeo",
  "Visible": "表示",
  "Visitors": "訪問者",
  "Visitors and Pageviews": "訪問者とページビュー",
  "Waitlist": "ウェイトリスト",
  "Watch Tutorials": "チュートリアルを見る",
  "Weight": "太さ",
  "Well-Known Files": "既知のファイル",
  "Words": "単語",
  "Workshop": "ワークショップ",
  "Wrap": "折り返し",
  "Year": "年",
  "YouTube": "YouTube",
  
  // 日付・時刻
  "10d ago": "10日前",
  "12/24/25 · 11:05 AM": "2025年12月24日 11:05",
  "12/24/25, 3:01 AM": "2025年12月24日 3:01",
  "Dec 11, 2025": "2025年12月11日",
  "Dec 3": "12月3日",
  "Dec 7, 2025": "2025年12月7日",
  "Dec 8, 2025": "2025年12月8日",
  "Jan 2": "1月2日",
  "January 2026": "2026年1月",
  
  // 言語・国
  "English": "英語",
  "French": "フランス語",
  "German": "ドイツ語",
  "United States": "アメリカ合衆国",
  "United Kingdom": "イギリス",
  "Japan": "日本",
  
  // イージング
  "Back In": "バックイン",
  "Back In Out": "バックインアウト",
  "Back Out": "バックアウト",
  "Bounce": "バウンス",
  
  // 図形
  "Arc": "アーク",
  "Bezier": "ベジエ",
  "Oval": "楕円",
  "Polygon": "ポリゴン",
  "Rectangle": "長方形",
  "Squircle": "スクワークル",

  // グラデーションタイプ
  "Pointer": "ポインター",
  "Radial": "放射状",
  "Conic": "円錐形",

  // ブレンドモード
  "Blending": "ブレンド",
  "Normal": "通常",
  "Darken": "暗く",
  "Multiply": "乗算",
  "Color Burn": "焼き込みカラー",
  "Lighten": "明るく",
  "Screen": "スクリーン",
  "Color Dodge": "覆い焼きカラー",
  "Overlay": "オーバーレイ",
  "Soft Light": "ソフトライト",
  "Hard Light": "ハードライト",
  "Difference": "差の絶対値",
  "Exclusion": "除外",
  "Luminosity": "輝度",

  // フィルター
  "BG Blur": "背景ぼかし",
  "Contrast": "コントラスト",
  "Grayscale": "グレースケール",
  "Invert": "反転",
  "Saturate": "彩度",
  "Sepia": "セピア",

  // 3D・トランスフォーム
  "Composite": "コンポジット",
  "Mode": "モード",
  "Luminance": "輝度",
  "Depth": "深度",
  "Perspective": "遠近感",
  "Origin": "原点",
  "Backface": "裏面",
  "Preserve 3D": "3D保持",

  // 位置アンカー
  "Top Left": "左上",
  "Top Center": "上中央",
  "Top Right": "右上",
  "Bottom Left": "左下",
  "Bottom Center": "下中央",
  "Bottom Right": "右下",

  // サイズ制約
  "Min Width": "最小幅",
  "Min Height": "最小高さ",
  "Max Height": "最大高さ",

  // オーバーフロー
  "Overflow X": "横方向のはみ出し",
  "Overflow Y": "縦方向のはみ出し",

  // カーソル設定
  "Web Cursor": "Webカーソル",
  "Pick a default cursor": "デフォルトカーソルを選択",
  "Custom Cursor": "カスタムカーソル",
  "Pick a component": "コンポーネントを選択",
  "Animate your cursor": "カーソルをアニメーション",

  // インタラクション
  "Set Variant": "バリアントを設定",
  "Set Variable": "変数を設定",
  "Reset Variables": "変数をリセット",
  "Parameters": "パラメーター",
  "Draggable": "ドラッグ可能",
  "Follow": "フォロー",
  "Tap Color": "タップカラー",
  "User Select": "ユーザー選択",
  "Dropdowns popovers": "ドロップダウン/ポップオーバー",
  "Modals toasts videos": "モーダル/トースト/動画",

  // フロー
  "Flow": "フロー",
  "Effect": "エフェクト",
  "Flow Effect": "フローエフェクト",

  // エクスポート
  "Export Image": "画像をエクスポート",
  "Export Stack": "スタックをエクスポート",
  "Fit Image": "画像をフィット",
  "Offset Y": "オフセットY",

  // メニュー要素
  "Menu Arrow": "メニュー矢印",
  "Menu Checkmark": "メニューチェックマーク",

  // テキスト
  "Balance": "バランス",
  "Truncate": "切り捨て",

  // API・フェッチ
  "Add Fetch": "フェッチを追加",
  "Fetch": "フェッチ",
  "Advanced": "詳細設定",

  // アクセシビリティ
  "Accessibility Tips": "アクセシビリティのヒント",
  "Aria Label": "Ariaラベル",
  "Tab Index": "タブインデックス",
  "Google Bot": "Googleボット",
  "Skip (data-nosnippet)": "スキップ (data-nosnippet)",
  "Include (default)": "含める（デフォルト）",
  "Skip": "スキップ",
};

// 重複処理防止：翻訳済みのノードを記録
const translatedNodes = new WeakSet<Node>();
const unknownWords = new Set<string>();

/**
 * window.missingList を更新（コンソールからアクセス用）
 */
const updateMissingList = () => {
  (window as any).missingList = Array.from(unknownWords).sort();
};

/**
 * 翻訳の実行エンジン
 */
const translate = () => {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;

  while (node = walker.nextNode()) {
    // 翻訳済みの場合はスキップ
    if (translatedNodes.has(node)) continue;

    const text = node.nodeValue?.trim();
    if (!text || text.length < 2) continue;

    // 1. 辞書にヒットする場合
    if (translations[text]) {
      const translatedText = translations[text];
      if (node.nodeValue !== translatedText) {
        node.nodeValue = translatedText;
        translatedNodes.add(node);
        // 親に属性を付与（任意）
        if (node.parentElement) {
          node.parentElement.setAttribute("data-translated", "true");
        }
      }
    } 
    // 2. 辞書にない英語ラベル（未翻訳発見ログ）
    else if (/[a-zA-Z]/.test(text) && text.length < 40) {
      if (!unknownWords.has(text)) {
        unknownWords.add(text);
        console.log("📝 未翻訳発見:", text);
        updateMissingList();
      }
    }
  }
};

/**
 * MutationObserver による動的監視
 */
const observer = new MutationObserver((mutations) => {
  let shouldProcess = false;
  for (const mutation of mutations) {
    if (mutation.addedNodes.length > 0) {
      shouldProcess = true;
      break;
    }
  }
  if (shouldProcess) translate();
});

// 監視開始
observer.observe(document.body, {
  childList: true,
  subtree: true
});

// 初期実行
translate();
updateMissingList();

// バックグラウンドでの定期実行（安全策）
setInterval(translate, 3000);